channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.6.10
  - tensorflow-gpu=1.14
  - pip:
    - annoy==1.16.2
    - art==4.2
    - attrs==19.3.0
    - autopep8==1.5.3
    - backcall==0.1.0
    - beautifulsoup4==4.8.1
    - bert4keras==0.7.3
    - bleach==3.1.4
    - boto==2.49.0
    - boto3==1.10.28
    - botocore==1.13.28
    - chardet==3.0.4
    - click==7.0
    - coverage==4.5.4
    - cycler==0.10.0
    - dask==2.10.1
    - datasets==2.4.0
    - decorator==4.4.2
    - defusedxml==0.6.0
    - demjson==2.2.4
    - docutils==0.15.2
    - emoji==0.5.4
    - entrypoints==0.3
    - et-xmlfile==1.0.1
    - fasttext==0.9.1
    - flashtext==2.7
    - fsspec==0.6.2
    - gensim==3.8.1
    - idna==2.8
    - importlib-metadata==1.6.0
    - ipykernel==5.2.1
    - ipython==7.13.0
    - ipython-genutils==0.2.0
    - ipywidgets==7.4.2
    - jdcal==1.4.1
    - jedi==0.17.0
    #- jieba==0.39
    - jinja2==2.11.2
    - jmespath==0.9.4
    - joblib==0.14.0
    - jpype1==0.7.0
    - json5==0.8.5
    - jsonschema==3.2.0
    - jupyter-client==5.2.4
    - jupyter-console==6.0.0
    - jupyter-contrib-core==0.3.3
    - jupyter-contrib-nbextensions==0.5.1
    - jupyter-core==4.4.0
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-latex-envs==1.4.6
    - jupyter-nbextensions-configurator==0.4.1
    - jupyterlab==1.1.4
    - jupyterlab-server==1.0.6
    - keras==2.2.4
    - keras-bert==0.80.0
    - keras-embed-sim==0.7.0
    - keras-layer-normalization==0.14.0
    - keras-multi-head==0.22.0
    - keras-pos-embd==0.11.0
    - keras-position-wise-feed-forward==0.6.0
    - keras-self-attention==0.41.0
    - keras-transformer==0.31.0
    - kiwisolver==1.1.0
    - langid==1.1.6
    - locket==0.2.0
    - lxml==4.4.2
    - markupsafe==1.1.1
    - matplotlib==3.1.2
    - mistune==0.8.4
    - mock==3.0.5
    - nbconvert==5.6.1
    - nbformat==5.0.6
    #- nltk==3.4.5
    - notebook==5.7.4
    - openpyxl==3.0.0
    - packaging==20.4
    - pandas==0.23.4
    - pandocfilters==1.4.2
    - parso==0.7.0
    - partd==1.1.0
    - pep8==1.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.7.1
    - prompt-toolkit==2.0.10
    - ptyprocess==0.6.0
    - pybind11==2.5.0
    - pycm==2.5
    - pycodestyle==2.6.0
    - pygments==2.6.1
    # - pyhanlp==0.1.57
    - pyparsing==2.4.5
    - pyrsistent==0.16.0
    - python-dateutil==2.8.0
    #- pytorch-transformers==1.2.0
    - pytz==2019.3
    - pyyaml==5.1.2
    - pyzmq==19.0.0
    - rank-bm25==0.2
    - regex==2019.11.1
    - requests==2.22.0
    - s3transfer==0.2.1
    - sacremoses==0.0.35
    - scikit-learn==0.19.2
    - send2trash==1.5.0
    - sentencepiece==0.1.83
    - setuptools==57.5.0
    - sklearn-pandas==1.8.0
    - sklearn2pmml==0.50.1
    - smart-open==1.9.0
    - soupsieve==1.9.5
    - terminado==0.8.3
    - testpath==0.4.4
    - tensorflow-serving-api==1.14
    - toml==0.10.1
    - toolz==0.10.0
    #- torch==1.3.1
    - tornado==5.1.1
    - tqdm==4.28.1
    - traitlets==4.3.3
    - transformers[torch]==4.18.0
    - urllib3==1.25.7
    - wcwidth==0.1.9
    - webencodings==0.5.1
    - whoosh==2.7.4
    - widgetsnbextension==3.4.2
    - xgboost==0.80
    - xlrd==1.2.0
    - xlsxwriter==1.2.5
    - xlwt==1.3.0
    - zeras==0.4.4
    - zhconv==1.4.3
    - zipp==3.1.0
