channels:
  - defaults
dependencies:
  - pip=20.0.2
  - python=3.7
  - tensorflow=2.3.0 # tensorflow 和 CUDA 兼容表 https://www.tensorflow.org/install/source#tested_build_configurations
  - pytorch::pytorch=1.11.0
  - cudatoolkit=10.2
  - cudnn=7
  - pip:
    - aiohttp==3.8.3
    - aiosignal==1.2.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - async-generator==1.10
    - async-timeout==4.0.2
    - asynctest==0.13.0
    - attrs==22.1.0
    - autopep8==1.5.3
    - backcall==0.2.0
    - bleach==4.1.0
    - cffi==1.15.1
    - charset-normalizer==2.0.12
    - click==8.0.4
    - datasets==2.4.0
    - decorator==5.1.1
    - defusedxml==0.7.1
    - dill==0.3.4
    - entrypoints==0.4
    - faiss-gpu==1.7.0
    - filelock==3.4.1
    - frozenlist==1.2.0
    - fsspec==2022.1.0
    - gensim==3.8.1
    - huggingface-hub==0.4.0
    - idna==3.4
    - idna-ssl==1.1.0
    - importlib-resources==5.4.0
    - ipykernel==5.5.6
    - ipython==7.16.3
    - ipython-genutils==0.2.0
    - ipywidgets==7.7.2
    - jedi==0.17.2
    - jinja2==3.0.3
    - joblib==0.14.0
    - jsonschema==3.2.0
    - jupyter==1.0.0
    - jupyter-client==7.1.2
    - jupyter-console==6.4.3
    - jupyter-contrib-core==0.4.2
    - jupyter-contrib-nbextensions==0.7.0
    - jupyter-core==4.9.2
    - jupyter-highlight-selected-word==0.2.0
    - jupyter-nbextensions-configurator==0.6.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.1.1
    - keras==2.2.4 # kera 和 TensorFlow 版本兼容表 https://github.com/keras-team/keras
    - lxml==4.9.1
    - markupsafe==2.0.1
    - mistune==0.8.4
    - multidict==5.2.0
    - multiprocess==0.70.12.2
    - nbclient==0.5.9
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.6
    - notebook==6.4.10
    - packaging==21.3
    - pandas==0.23.4
    - pandocfilters==1.5.0
    - parso==0.7.1
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.32
    - ptyprocess==0.7.0
    - pyarrow==6.0.1
    - pycodestyle==2.9.1
    - pycparser==2.21
    - pygments==2.13.0
    - pyparsing==3.0.9
    - pyrsistent==0.18.0
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - pyzmq==24.0.1
    - qtconsole==5.2.2
    - qtpy==2.0.1
    - regex==2022.10.31
    - requests==2.27.1
    - responses==0.17.0
    - sacremoses==0.0.53
    - scikit-learn==0.19.2
    - send2trash==1.8.0
    - setuptools==57.5.0
    - sklearn-pandas==1.8.0
    - smart-open==6.2.0
    - terminado==0.12.1
    - testpath==0.6.0
    - tokenizers==0.12.1
    - toml==0.10.2
    - tornado==6.1
    - tqdm==4.64.1
    - traitlets==4.3.3
    - transformers==4.18.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - widgetsnbextension==3.6.1
    - xxhash==3.1.0
    - yarl==1.7.2